adminUser:
  password: vault:dcanadillas-cjxd/adminUser:password
  username: dcanadillas
enableDocker: false
pipelineUser:
  email: dcanadillas@cloudbees.com
  token: vault:dcanadillas-cjxd/pipelineUser:token
  username: dcanadillas-kubecd
prow:
  hmacToken: vault:dcanadillas-cjxd/prow:hmacToken
